services:
  mysql:
    image: mysql:8.0
    container_name: mercadofacil-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ab12c3
      MYSQL_DATABASE: mercadofacil
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mercadofacil-api:
    container_name: mercadofacil-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MercadoFacilDB: "Server=mysql;Port=3306;Database=mercadofacil;User=root;Password=ab12c3;"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
